name: 'greeting'
description: 'a hello world action'

inputs:
  name:
    description: 'the name to use in greeting'
    required: true

outputs:
  result:
    description: ''
    value: ${{ steps.main.outputs.result }}

runs:
  using: 'composite'

  steps:
    - id: main
      shell: bash
      run: |
        echo "result=hello, ${{ inputs.name }}!" >> $GITHUB_OUTPUT
