name: 'smoke-test'
description: 'checking for a specific end-point'

inputs:
  version:
    description: 'version to check for'
    required: true
  wait_interval:
    description: 'amount of seconds to wait between each health check'
    default: '3'

runs:
  using: 'composite'

  steps:
    - shell: bash
      run: sh ./actions/smoke-test/action.sh ${{ inputs.version }} ${{ inputs.wait_interval }}
