name: Main

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: './actions/greeting'
        id: greeting
        with:
          name: 'erick'

      - run: |
          echo 'results of previous step'
          echo ${{ steps.greeting.outputs.result }}

  job2:
    uses: './workflows/create-an-artifact.yaml'
