name: 'reusable'

on:
  workflow_call:
    inputs:
      name:
        description: "name"
        type: string
        required: true

jobs:

  reusable:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo 'Hello, ${{ inputs.name }}'
